//Recursion - Subsets / Subsequences of String 

                                           /* SUBSETS */

// ek set de rahka hai hume uska power set i.e all  subset of the set return karna hai
//  wen knoe for a set with n number power set ha 2^n ellemnt 

// leetcode ques link --> https://leetcode.com/problems/subsets/


                                            /*SUBSEQUENCES*/

//A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
//link ques -->https://www.codingninjas.com/codestudio/problems/subsequences-of-string_985087?leftPanelTab=0&utm_source=youtube&utm_medium=affiliate&utm_campaign=love_babbar_16

///basically same type of ques hai uppar vala jaise as if lenegth of string is n then totaol subsequences at=re 2^n
//see how recusion tree made link fo video -->https://www.youtube.com/watch?v=V0IgCltYgg4&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA&index=42&ab_channel=CodeHelp-byBabbar

///h.w --> how to solve both the ques by using bits 



                                           /* VVVIMP */

// YEAH JO POWER SET PE BASED QUES HAI YEAH BAHUT IMP HAI KYUKI ISKE BAHUT TAREKE HAI SOLVE KARNE KE ITERATIVE , RECURSIVE , BIT MASKING 
// IS TOPIC PE GFG MAI 3 -4 ARTICLE HAI ALALG ALAG METHOD DISCUSS KIYA HAI JAHA 

//solution of homw work i.e find power set using bit mmasking 
//  see this video to understanf the approach 
//https://www.youtube.com/watch?v=b7AYbpM5YrE&ab_channel=takeUforward
//https://www.youtube.com/watch?v=gUxpKm0btH0&ab_channel=Luv